seaboxdata:
  rsp:
    hostname: 

spring:
  redis:
#    database: 0
    host: cloud.dfjx.com
    port: 6379
    password: dfjx123
    jedis:
      pool:
        max-active: 100
        max-wait: 2000
        max-idle: 500
        min-idle: 8
    timeout: 5000
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/mysql?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
          username: root
          password: 123456
          driverClassName: com.mysql.cj.jdbc.Driver
        corc:
          url: jdbc:mysql://127.0.0.1:3306/hlbe?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
          username: root
          password: 123456
          driverClassName: com.mysql.cj.jdbc.Driver
#接口地址
interface:
#算法
  program:
    typenames: http://10.1.1.233:8010/saim/v1/interactive/getalgtype
    programDetail: http://10.1.1.233:8010/saim/v1/interactive/alginfo
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 30000
  ConnectTimeout: 30000

auth:
  need: true #是否对接auth，false为暂时不对接，true为开启对接
  versions: auth1 #对接权限管理版本auth1、auth2，
  systemCode: template #本系统在auth的auth_system或者oauth_system中配置的system_code或者app_name

#template服务地址，本服务可以不用配置
template-service-url: http://ac.ztdemo.com

#用户中心服务地址
auth-service-url: http://ac.ztdemo.com

#认证中心服务地址
auth-server-url: http://ac.ztdemo.com
security:
  oauth2:
    client:
      client-id: testclientid
      client-secret: 123456
      scope: read_userinfo
      access-token-uri: ${auth-server-url}/oauth/token
      user-authorization-uri: ${auth-server-url}/oauth/authorize
    resource:
      token-info-uri: ${auth-server-url}/oauth/check_token
      check-token: ${auth-server-url}/oauth/check_token

#token存储方式和时间，为false是关闭浏览cookie就消失，true存储cookie，access-cookie-time为有效时间
cookie:
  enable: true
  access-cookie-time: 600000

web:
  home: http://my.dfjx.com:3071

#domain，cookie存储的主域名，有效时间  10.60.78.33
token:
  domain: dfjx.com
  access-token:
    expiration-time: 600000
  refresh-token:
    expiration-time: 2592000 # 60 * 60 * 12 * 2 * 30

#日志级别
logging:
  level:
    "org.springframework": info
    com.seaboxdata.hlbejk.service.modules.dao: debug